remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [SWAPNIL JOSHI]
description: [I'm a dedicated Mechanical Engineer with expertise in product design, manufacturing processes, and automation systems. Having pursued Master's degree at Clemson University, I bring hands-on experience in optimizing manufacturing processes and developing innovative engineering solutions.]
